### ISSUE TITLE
error

### ISSUE THREAD

**Issue by destiansatya** [alvinoktavianus/Maiga#3]
vin ada error di admin untuk upload
![err](https://cloud.githubusercontent.com/assets/19955495/16169835/1a3919e6-3567-11e6-9237-9aa4e937d36d.PNG)

**Comment by alvinoktavianus** [comment]
ohh lu mesti ketik ini dulu ```php artisan migrate``` di console, soalnya databasenya gw edit
udh gitu, buka phpmyadmin, klik database maiga nya, pilih SQL, trus masukin query ini
```UPDATE payrolls SET isdownloaded = 'N' WHERE email = '<email>'``` dengan ```<email>``` adalah alamat email user (misalnya test123@gmail.com)
